### ISSUE TITLE
calling 'keys' method doesn't clean up expirations at first.

### ISSUE THREAD

**Issue by internety** [mailgun/expiringdict#14]
example:

``` python
from expiringdict import ExpiringDict
from time import sleep

expirationtest = ExpiringDict(max_len=100, max_age_seconds=5)
expirationtest["testing123"]="somedata"
print expirationtest.keys()
sleep(6)
print expirationtest.keys()
```

above example will print 'testing123' twice.

i am using python 2.7.10 and freshly installed expiringdict (via pip)

**Comment by internety** [comment]
sorry, should be 
```
expirationtest["testing123"]='somedata'
```

**Comment by mdelcambre** [comment]
From the readme, this appears to be known and potetially intended.
>Note: Iteration over dict and also keys() do not remove expired values!

**Comment by internety** [comment]
You have right. Didn't noticed that before....
