### ISSUE TITLE
Upload v1.1.4 to PyPi

### ISSUE THREAD

**Issue by RyPeck** [mailgun/expiringdict#26]
The latest version in this repo is 1.1.4 with Python 3 support. PyPi only has 1.1.3. Anything you need to get this published out to PyPi?

**Comment by djstein** [comment]
@horkhe @jeremyschlatter @svisser @defcube @russjones @anton-efimenko  can someone push this to PyPi. Is anyone pushing code up at MailGun right now? This is a dependency in your https://github.com/mailgun/flanker application as well, is that abandoned for Python 3 support?

**Comment by svisser** [comment]
I'm not able to upload a package for this project to PyPI.

If you're able, you may be able to solve your use cases with https://pypi.python.org/pypi/ttldict which does have Python 3.x support.

**Comment by lxylxy123456** [comment]
It seems that the packet cannot be installed with pip3, since `import md5` was not fixed.

**Comment by TRManderson** [comment]
@svisser ttldict is not a sufficient replacement, primarily because the `.get` method doesn't return anything on a successful `get`.

**Comment by svisser** [comment]
@TRManderson a pull request to fix that was opened a week ago: https://github.com/mobilityhouse/ttldict/pull/3

**Comment by oz123** [comment]
@TRManderson a new version of TTLDict (0.3) is available in PyPI!

**Comment by Wenzel** [comment]
Hi !
I would need `expiringdict >= 1.1.4` and Python3 compatible for porting `Rekall`.

Anything blocking you ?
Anyone could upload it ?

Thanks ! :)

**Comment by horkhe** [comment]
Uploaded, sorry for the hold up. Please let me know if it works for you.

**Comment by Wenzel** [comment]
Works for me.
Thanks a lot @horkhe :1st_place_medal:
