### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ecederstrand** [mailgun/expiringdict#33]
@mailgun There are a few outstanding issues and PRs in the tracker that have gone unanswered, and Python3 support is just waiting for an official release on PyPI.

I'm volunteering to fix issues, test and merge code, cut releases etc. if you need help.

**Comment by ecederstrand** [comment]
@horkhe You seem to be the only person from Mailgun active on GitHub. What can I do to help here?

**Comment by horkhe** [comment]
Hi Erik, I do not think any of us is interested in improving this project for two reasons: 1) it does all we need; 2) we are shifting our focus towards Golang. But if you are really interested in keeping it alive I think we can grant you merge permissions. We already have positive experience with community maintainers for other Mailgun projects. I will raise this question with my management and get back to you later today.

**Comment by ecederstrand** [comment]
Hi @horkhe Thanks for the explanation on the situation and your position. Merge permissions would be great!

**Comment by horkhe** [comment]
@ecederstrand i got general consent from the management. Let's do it the following way: please submit a couple of PRs first and make me a reviewer. I promise to review in timely manner. If I like what I see we will give you merge permissions. Does it work for you?

**Comment by ecederstrand** [comment]
That’s fine with me. Thanks!

**Comment by ecederstrand** [comment]
I'm no longer using this package. Closing.
